// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Server.Data;

#nullable disable

namespace TMS.Server.Migrations
{
    [DbContext(typeof(TransitDbContext))]
    [Migration("20260714062440_SeedStations")]
    partial class SeedStations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RailLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light Rail Transit Line 1",
                            PrimaryColor = "#009639",
                            ShortName = "LRT-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light Rail Transit Line 2",
                            PrimaryColor = "#7B1FA2",
                            ShortName = "LRT-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metro Rail Transit Line 3",
                            PrimaryColor = "#005EB8",
                            ShortName = "MRT-3"
                        });
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RailLineId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RailLineId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.HasOne("TMS.Server.Models.RailLine", "RailLine")
                        .WithMany("Stations")
                        .HasForeignKey("RailLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RailLine");
                });

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
