// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Server.Data;

#nullable disable

namespace TMS.Server.Migrations
{
    [DbContext(typeof(TransitDbContext))]
    [Migration("20260714070334_AddMoreMRT3Stations")]
    partial class AddMoreMRT3Stations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RailLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light Rail Transit Line 1",
                            PrimaryColor = "#009639",
                            ShortName = "LRT-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light Rail Transit Line 2",
                            PrimaryColor = "#7B1FA2",
                            ShortName = "LRT-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metro Rail Transit Line 3",
                            PrimaryColor = "#005EB8",
                            ShortName = "MRT-3"
                        });
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RailLineId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RailLineId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 14.6549,
                            Longitude = 121.0304,
                            Name = "North Avenue",
                            RailLineId = 3,
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 14.6426,
                            Longitude = 121.0389,
                            Name = "Quezon Avenue",
                            RailLineId = 3,
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 14.6348,
                            Longitude = 121.0438,
                            Name = "GMA Kamuning",
                            RailLineId = 3,
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 14.622,
                            Longitude = 121.05670000000001,
                            Name = "Araneta Center-Cubao",
                            RailLineId = 3,
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 14.610900000000001,
                            Longitude = 121.0561,
                            Name = "Santolan-Annapolis",
                            RailLineId = 3,
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 14.586600000000001,
                            Longitude = 121.056,
                            Name = "Ortigas",
                            RailLineId = 3,
                            SequenceNumber = 6
                        });
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.HasOne("TMS.Server.Models.RailLine", "RailLine")
                        .WithMany("Stations")
                        .HasForeignKey("RailLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RailLine");
                });

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
