// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Server.Data;

#nullable disable

namespace TMS.Server.Migrations
{
    [DbContext(typeof(TransitDbContext))]
    [Migration("20260714071529_AddLRT2Stations")]
    partial class AddLRT2Stations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RailLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light Rail Transit Line 1",
                            PrimaryColor = "#009639",
                            ShortName = "LRT-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light Rail Transit Line 2",
                            PrimaryColor = "#7B1FA2",
                            ShortName = "LRT-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metro Rail Transit Line 3",
                            PrimaryColor = "#005EB8",
                            ShortName = "MRT-3"
                        });
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RailLineId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RailLineId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 14.6549,
                            Longitude = 121.0304,
                            Name = "North Avenue",
                            RailLineId = 3,
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 14.6426,
                            Longitude = 121.0389,
                            Name = "Quezon Avenue",
                            RailLineId = 3,
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 14.6348,
                            Longitude = 121.0438,
                            Name = "GMA Kamuning",
                            RailLineId = 3,
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 14.622,
                            Longitude = 121.05670000000001,
                            Name = "Araneta Center-Cubao",
                            RailLineId = 3,
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 14.610900000000001,
                            Longitude = 121.0561,
                            Name = "Santolan-Annapolis",
                            RailLineId = 3,
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 14.586600000000001,
                            Longitude = 121.056,
                            Name = "Ortigas",
                            RailLineId = 3,
                            SequenceNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 14.5176,
                            Longitude = 120.9971,
                            Name = "Baclaran",
                            RailLineId = 1,
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 14.524900000000001,
                            Longitude = 120.99250000000001,
                            Name = "EDSA",
                            RailLineId = 1,
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 14.5535,
                            Longitude = 120.9975,
                            Name = "Libertad",
                            RailLineId = 1,
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 14.5587,
                            Longitude = 120.9945,
                            Name = "Gil Puyat",
                            RailLineId = 1,
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 14.5624,
                            Longitude = 120.994,
                            Name = "Vito Cruz",
                            RailLineId = 1,
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 14.5702,
                            Longitude = 120.9918,
                            Name = "Quirino",
                            RailLineId = 1,
                            SequenceNumber = 6
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 14.5768,
                            Longitude = 120.98869999999999,
                            Name = "Pedro Gil",
                            RailLineId = 1,
                            SequenceNumber = 7
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 14.582700000000001,
                            Longitude = 120.9847,
                            Name = "United Nations",
                            RailLineId = 1,
                            SequenceNumber = 8
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 14.5891,
                            Longitude = 120.9817,
                            Name = "Central Terminal",
                            RailLineId = 1,
                            SequenceNumber = 9
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 14.599399999999999,
                            Longitude = 120.9798,
                            Name = "Carriedo",
                            RailLineId = 1,
                            SequenceNumber = 10
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 14.603899999999999,
                            Longitude = 120.983,
                            Name = "Recto",
                            RailLineId = 2,
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 14.601800000000001,
                            Longitude = 120.9928,
                            Name = "Legarda",
                            RailLineId = 2,
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 14.601000000000001,
                            Longitude = 121.0056,
                            Name = "Pureza",
                            RailLineId = 2,
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 14.604200000000001,
                            Longitude = 121.017,
                            Name = "V. Mapa",
                            RailLineId = 2,
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 14.610300000000001,
                            Longitude = 121.0198,
                            Name = "J. Ruiz",
                            RailLineId = 2,
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 14.6137,
                            Longitude = 121.0228,
                            Name = "Gilmore",
                            RailLineId = 2,
                            SequenceNumber = 6
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 14.618499999999999,
                            Longitude = 121.02809999999999,
                            Name = "Betty Go-Belmonte",
                            RailLineId = 2,
                            SequenceNumber = 7
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 14.6227,
                            Longitude = 121.04389999999999,
                            Name = "Araneta Center-Cubao",
                            RailLineId = 2,
                            SequenceNumber = 8
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 14.6287,
                            Longitude = 121.0643,
                            Name = "Anonas",
                            RailLineId = 2,
                            SequenceNumber = 9
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 14.630699999999999,
                            Longitude = 121.0722,
                            Name = "Katipunan",
                            RailLineId = 2,
                            SequenceNumber = 10
                        });
                });

            modelBuilder.Entity("TMS.Server.Models.Station", b =>
                {
                    b.HasOne("TMS.Server.Models.RailLine", "RailLine")
                        .WithMany("Stations")
                        .HasForeignKey("RailLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RailLine");
                });

            modelBuilder.Entity("TMS.Server.Models.RailLine", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
